### ISSUE TITLE
Success message blocks webpack to finish process

### ISSUE THREAD

**Issue by muuvmuuv** [RoccoC/webpack-build-notifier#45]
As you can read in this [issue on webpack](https://github.com/webpack/webpack/issues/9641) from me, webpack takes way to long to finish. We figured out that it is this plugin and the success message that causes the delay. I have seen that in #28 there was already something like that but that didn't help me.

**Comment by RoccoC** [comment]
Hi @muuvmuuv , thanks for the report!

Looks like this issue should be fixed in `node-notifier@5.4.1`: https://github.com/mikaelbr/node-notifier/pull/271

I just published a new version (1.1.1) that uptakes the node-notifier fix and it seems to be working on my Windows machine (I will test out on OS X a bit later). Let me know if it doesn't fix your issue!

**Comment by muuvmuuv** [comment]
That solved it, thanks!
